language: python
python:
  - "3.7"
  - "3.7.3"
  - "3.8"
# command to install dependencies
install:
  #- pip install requests pyyaml pytest pytest-cov
  - pip install .

# command to run tests
script:
  - pytest --cov=./